version: '3.6'

services:
    db:
        image: postgres:latest
        env_file:
            - ./postgres.env
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        mem_limit: 100m

    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile
            context: ./client
        env_file:
            - ./client/.env
        volumes:
            - /app/node_modules
            - ./client:/app
        mem_limit: 256m
        mem_reservation: 100M
        cpus: 0.5

    api:
        build:
            dockerfile: Dockerfile
            context: ./server
        env_file:
            - ./server/.env
        depends_on:
            - db
            - redis
        ports:
            - 4000:4000
        volumes:
            - /app/node_modules
            - ./server:/app
        mem_limit: 512m
        mem_reservation: 256M

    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '80:80'
        mem_limit: 156m

    redis:
        image: redis:6.2-alpine
        restart: always
        volumes:
            - redis:/var/lib/redis/data
        ports:
            - 6379:6379
    # pgadmin:
    #     image: dpage/pgadmin4
    #     container_name: pgadmin4_container
    #     restart: always
    #     ports:
    #         - '5050:80'
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: EMAIL
    #         PGADMIN_DEFAULT_PASSWORD: PASSWORD
    #     volumes:
    #         - pgadmin-data:/var/lib/pgadmin

volumes:
    postgres_data:
    redis:
    # pgadmin-data:
